const ADD_MOVIE = 'ADD_MOVIE';
const MOVIE_WATCHED = 'MOVIE_WATCHED';
const EDIT_MOVIE_NAME = 'EDIT_MOVIE_NAME';
const DELETE_MOVIE = 'DELETE_MOVIE';

export {
  ADD_MOVIE, MOVIE_WATCHED, EDIT_MOVIE_NAME, DELETE_MOVIE,
};
